window.screenOrientation = "sensor_landscape", 
// loadLib("libs/min/laya.core.min.js"), 
// loadLib("libs/min/laya.ani.min.js"), 
// loadLib("libs/min/laya.html.min.js"), 
// loadLib("libs/min/laya.particle.min.js"), 
// loadLib("libs/min/laya.ui.min.js"), 
// loadLib("libs/min/laya.d3.min.js"), 
loadLib("libs/min/laya.device.min.js"), 
loadLib("libs/min/domparserinone.min.js"), 
loadLib("libs/min/physic2d.min.js"), 
loadLib("js/main.js");